name: Build images
on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: opi5
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v1.33/ubuntu-22.04.3-preinstalled-server-arm64-orangepi-5.img.xz
          - name: opi5plus
            script: ./install_opi5.sh
            base_image: https://github.com/Joshua-Riek/ubuntu-rockchip/releases/download/v1.33/ubuntu-22.04.3-preinstalled-server-arm64-orangepi-5-plus.img.xz
    name: "Build for ${{ matrix.name }}"
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch tags
      run: git fetch --tags --force

    - uses: pguyot/arm-runner-action@HEAD
      id: install_deps
      with:
        image_additional_mb: 1500
        bind_mount_repository: true
        exit_on_fail: true
        base_image: ${{ matrix.base_image }}
        commands: |
          chmod +x ${{matrix.script}}
          bash ${{ matrix.script }}

    - name: Compress built image
      run: |
        mv ${{ steps.install_deps.outputs.image }} northstar_${{ matrix.name }}.img
        sudo xz -T 0 -v northstar_${{ matrix.name }}.img

    - uses: actions/upload-artifact@master
      with:
        name: northstar_${{ matrix.name }}.img.xz
        path: northstar_${{ matrix.name }}.img.xz
        if-no-files-found: error
        retention-days: 1
